### PR TITLE
ir_leds: update messages for diamond

### PR DESCRIPTION
**Pull request by moritz-diller**
remove 740nm support
add 850 center, side and 940 single

### CODE REVIEW

**Review by fouge — COMMENTED** [review]
should we keep 740 LED in any case on Pearl?
is it that important to completely remove it? 🤔

**Comment by moritz-diller** [comment]
> should we keep 740 LED in any case on Pearl? is it that important to completely remove it? 🤔

@jonny-str

**Comment by jonny-str** [comment]
> should we keep 740 LED in any case on Pearl? is it that important to completely remove it? 🤔
As the newest EV builds of pearl, dont have the 740nm LEDs anyway, it doesnt make much sense to have them. 
I asked Tobi Zillig and he said, he will not need the 740nm, not even for testing on old Pearl Orbs.
Removing them completly, enables the restructuration of the timer configuration to a setup the makes much more sence compared to the way it was before.

**Comment by fouge** [comment]
@jonny-str @moritz-diller ok agreed to simplify the logic :)

**Review by fouge — APPROVED** [review]

**Review by TheButlah — APPROVED** [review]

**Pull request merged**
